name: Build CI

on: 
  push:
    paths-ignore: 
      - README.md
      - LICENSE.txt

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        (Get-Content "node_modules/builder-util/out/util.js").Replace("^[\w","^[.\w")| out-file "node_modules/builder-util/out/util.js"
    - run: npm run lint
    - run: npm run electron:build
      env:
        CI: true
        GH_TOKEN: ${{ secrets.github_token }}
    - uses: actions/upload-artifact@v1
      with:
        name: ECUBus
        path: dist_electron/win-unpacked
    - uses: actions/upload-artifact@v1
      with:
        name: ECUBus.exe
        path: dist_electron/ECUBus.exe
