name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        (Get-Content "node_modules/builder-util/out/util.js").Replace("^[\w","^[.\w")| out-file "node_modules/builder-util/out/util.js"
    - run: npm run lint
    - name: Electron Builder Action
        uses: samuelmeuli/action-electron-builder@v1.3.0
        with:
          # GitHub authentication token
          github_token: ${{ secrets.github_token }}
          release: true
          build_script_name: electron:build
#     - run: npm run electron:build
#       env:
#         CI: true
#         GH_TOKEN: ${{ secrets.github_token }}
       
